### ISSUE TITLE
Push release 0.0.4 to Cocoapods.

### ISSUE THREAD

**Issue by jessesquires** [danwilliams64/DJWStarRatingView#8]
I see that release [0.0.4](https://github.com/danwilliams64/DJWStarRatingView/releases/tag/0.0.4) has been tagged, but it hasn't been pushed to CocoaPods yet.

http://cocoapods.org/?q=DJWStarRatingView

**Comment by danwilliams64** [comment]
Thanks for raising this, I've just pushed 0.0.4 to CocoaPods.

**Comment by jessesquires** [comment]
Thanks @danwilliams64 ! :+1:
